export const PARTY_FULL_NAMES: Record<string, string> = {
  TVK: "Tamilaga Vettri Kazhagam",
  DMK: "Dravida Munnetra Kazhagam",
  ADMK: "All India Anna Dravida Munnetra Kazhagam",
  AIADMK: "All India Anna Dravida Munnetra Kazhagam",
  INC: "Indian National Congress",
  PMK: "Pattali Makkal Katchi",
  BJP: "Bharatiya Janata Party",
  NTK: "Naam Tamilar Katchi",
  AMMK: "Amma Makkal Munnettra Kazagam",
  CPI: "Communist Party of India",
  "CPI(M)": "Communist Party of India (Marxist)",
  VCK: "Viduthalai Chiruthaigal Katchi",
  IUML: "Indian Union Muslim League",
  MDMK: "Marumalarchi Dravida Munnetra Kazhagam",
  DMDK: "Desiya Murpokku Dravida Kazhagam",
  IND: "Independent",
};

export const PARTY_COLORS: Record<string, string> = {
  TVK: "#FACC15",
  DMK: "#F97316",
  ADMK: "#22C55E",
  AIADMK: "#22C55E",
  INC: "#F97316",
  PMK: "#22C55E",
  BJP: "#22C55E",
  NTK: "#EF4444",
  AMMK: "#22C55E",
  CPI: "#F97316",
  "CPI(M)": "#F97316",
  VCK: "#F97316",
  IUML: "#F97316",
  MDMK: "#F97316",
  DMDK: "#F97316",
  IND: "#6B7280",
};

export const ALLIANCES: Record<string, string> = {
  DMK: "SPA Alliance",
  INC: "SPA Alliance",
  CPI: "SPA Alliance",
  "CPI(M)": "SPA Alliance",
  VCK: "SPA Alliance",
  MDMK: "SPA Alliance",
  DMDK: "SPA Alliance",
  IUML: "SPA Alliance",
  ADMK: "ADMK+ Alliance",
  AIADMK: "ADMK+ Alliance",
  BJP: "ADMK+ Alliance",
  PMK: "ADMK+ Alliance",
  AMMK: "ADMK+ Alliance",
  TVK: "TVK (Solo)",
  NTK: "NTK (Solo)",
};

export const ALLIANCE_COLORS: Record<string, string> = {
  "SPA Alliance": "#F97316",
  "ADMK+ Alliance": "#22C55E",
  "TVK (Solo)": "#FACC15",
  "NTK (Solo)": "#EF4444",
};

export const ECI_BASE =
  "https://results.eci.gov.in/ResultAcGenMay2026";

export const PARTY_LEADER_IMAGE: Record<string, { src: string; name: string }> = {
  TVK: { src: "/leaders/vijay.jpg", name: "Thalapathy Vijay" },
  DMK: { src: "/leaders/stalin.jpg", name: "MK Stalin" },
  AIADMK: { src: "/leaders/edappadi.jpg", name: "Edappadi K. Palaniswami" },
  ADMK: { src: "/leaders/edappadi.jpg", name: "Edappadi K. Palaniswami" },
};

export const TN_DISTRICTS = [
  "Chennai",
  "Tiruvallur",
  "Kanchipuram",
  "Chengalpattu",
  "Vellore",
  "Ranipet",
  "Tiruvannamalai",
  "Villupuram",
  "Kallakurichi",
  "Salem",
  "Namakkal",
  "Erode",
  "The Nilgiris",
  "Coimbatore",
  "Tiruppur",
  "Dindigul",
  "Karur",
  "Tiruchirappalli",
  "Perambalur",
  "Ariyalur",
  "Cuddalore",
  "Nagapattinam",
  "Tiruvarur",
  "Thanjavur",
  "Pudukkottai",
  "Sivaganga",
  "Madurai",
  "Theni",
  "Virudhunagar",
  "Ramanathapuram",
  "Thoothukudi",
  "Tirunelveli",
  "Kanniyakumari",
  "Tenkasi",
  "Dharmapuri",
  "Krishnagiri",
];
